version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.cakephp
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./cakephp:/var/www/html
    environment:
      - USER=cakephp_user
    #command: ["/bin/bash", "-c", "groupadd -g ${HOST_GID} cakephp_group && useradd -u ${HOST_UID} -g ${HOST_GID} -m ${DOCKER_USER:-cakephp_user} && chown -R ${DOCKER_USER:-cakephp_user}:cakephp_group /var/www/html && su ${DOCKER_USER:-cakephp_user} -c '/usr/local/bin/docker-php-entrypoint apache2-foreground'"]
    #command: ["/bin/bash", "-c", "chown -R ${DOCKER_USER:-cakephp_user}:cakephp_group /var/www/html && su ${DOCKER_USER:-cakephp_user} -c '/usr/local/bin/docker-php-entrypoint apache2-foreground'"]
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: cakephp
      POSTGRES_PASSWORD: cakephp
      POSTGRES_DB: cakephp
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
